version: '2'

services:
  network-logger:
    image: network-logger
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      APP_PORT: 6000
      HTTPS: "true"

