apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    pod: pod-b
  name: pod-b-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-b
  strategy: {}
  template:
    metadata:
      labels:
        pod: pod-b
    spec:
      containers:
      - image: stakater/network-logger
        name: pod-b-app
        env:
          - name: APP_PORT
            value: "6000"
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
        resources: {}
