apiVersion: v1
kind: Service
metadata:
  labels:
    pod: pod-b
  name: pod-b-service
spec:
  ports:
  - port: 6000
    targetPort: 6000
    name: http
    protocol: TCP
  selector:
    pod: pod-b
  type: NodePort
