apiVersion: v1
kind: Service
metadata:
  labels:
    pod: pod-a
  name: pod-a-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
    protocol: TCP
  selector:
    pod: pod-a
  type: NodePort
