apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    pod: pod-a
  name: pod-a-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-a
  strategy: {}
  template:
    metadata:
      labels:
        pod: pod-a
    spec:
      containers:
      - image: stakater/network-logger
        name: pod-a-app
        env:
          - HTTPS: "true"
          - name: APP_PORT
            value: "5000"
          - name: POD_B_ROUTE
            value:
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources: {}
